version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    develop:
      watch:
        - action: rebuild
          path: ./frontend

  backend:
    build:
      context: ./backend/API
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: rebuild
          path: ./backend/API