services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    develop:
      watch:
        - action: rebuild
          path: ./frontend

  backend:
    env_file:
        - .env
    build:
      context: ./backend/API
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};
    volumes:
        - ./backend:/API
    develop:
      watch:
        - action: rebuild
          path: ./backend/API

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - db-data:/var/opt/mssql
      - ./Scripts:/Scripts
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_DATABASE: ${DB_NAME}
      MSSQL_USER: ${DB_USER}
      MSSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1433:1433"
    


volumes:
  db-data:
